export type EmployeePositionSeed = {
  nameKey: string;
  position: string;
  sheet: string;
};

export const EMPLOYEE_POSITIONS_2026: EmployeePositionSeed[] = [
  { nameKey: "มาลัยปานทอง", position: "QC line", sheet: "P01" },
  { nameKey: "มุณีสายกลิ่น", position: "หัวหน้าทีมบรรจุ", sheet: "P01" },
  { nameKey: "สำรวยเหล่าผา", position: "หัวหน้าทีมบรรจุ", sheet: "P01" },
  { nameKey: "สงวนวงศ์ยิ้มสะอาด", position: "หัวหน้าทีมบรรจุ", sheet: "P01" },
  { nameKey: "ถินก้านทอง", position: "พนักงานผสม", sheet: "P01" },
  { nameKey: "สุทัศน์แสงอินทร์", position: "หัวหน้าทีมผสม", sheet: "P01" },
  { nameKey: "ดนตรีก๋งแก้ว", position: "พนักงานผสม", sheet: "P01" },
  { nameKey: "กิตติภณแซ่ซุ้ง", position: "พนักงานผสม", sheet: "P01" },
  { nameKey: "อุไรวรรณจันทร์ลอย", position: "พนักงานบรรจุ", sheet: "P01" },
  { nameKey: "ปณัชช์เอี่ยมเอม", position: "พนักงานบรรจุ", sheet: "P01" },
  { nameKey: "อัญชเกดอุปสิทธิ์", position: "พนักงานบรรจุ", sheet: "P01" },
  { nameKey: "กาญจนาล้อมสินทรัพย์", position: "พนักงานบรรจุ", sheet: "P01" },
  { nameKey: "ศราวณีสุกสี", position: "พนักงานบรรจุ", sheet: "P01" },
  { nameKey: "วราใจเยือกเย็น", position: "พนักงานบรรจุ", sheet: "P01" },
  { nameKey: "ทัศพรมณีพันธ์", position: "พนักงานบรรจุ", sheet: "P01" },
  { nameKey: "สันติแก้วบุญเพิ่ม", position: "พนักงานบรรจุ", sheet: "P01" },
  { nameKey: "ธนวัฒน์กลิ่นขจร", position: "พนักงานบรรจุ", sheet: "P01" },
  { nameKey: "วาสนาชั้นสกุณี", position: "พนักงานเอกสาร", sheet: "P02" },
  { nameKey: "แสงทองกองสี", position: "QC line", sheet: "P02" },
  { nameKey: "พิชิตพัดเย็น", position: "พนักงานผสม", sheet: "P02" },
  { nameKey: "นุชานนท์ใจบุญ", position: "พนักงานชั่งวัตถุดิบ", sheet: "P02" },
  { nameKey: "พรรณีออมใช้", position: "หัวหน้าทีมบรรจุ", sheet: "P02" },
  { nameKey: "ไพรัชอยู่มากญาติ", position: "พนักงานขับรถโฟคลิฟท์", sheet: "P02" },
  { nameKey: "พรพิทักษ์จันทร์ตราชู", position: "พนักงานขับรถโฟคลิฟท์", sheet: "P02" },
  { nameKey: "ปาลิตาอุไรงาม", position: "พนักงานยิงกระสอบ", sheet: "P02" },
  { nameKey: "ชิดดนัยใจหลัก", position: "พนักงานผสม", sheet: "P02" },
  { nameKey: "นิธิธีร์ไพโรจน์", position: "พนักงานผสม", sheet: "P02" },
  { nameKey: "สถาพรเกียงยง", position: "พนักงานผสม", sheet: "P02" },
  { nameKey: "ธีระศักดิ์ดวงรัตน์", position: "พนักงานผสม", sheet: "P02" },
  { nameKey: "กฤษฎาพัฒน์เจริญรอย", position: "พนักงานผสม", sheet: "P02" },
  { nameKey: "วุฒิวสุคำสุข", position: "พนักงานผสม", sheet: "P02" },
  { nameKey: "ฉัตรศิริพันที", position: "พนักงานบรรจุ", sheet: "P02" },
  { nameKey: "การเกดพริ้งเพชร", position: "พนักงานบรรจุ", sheet: "P02" },
  { nameKey: "เกวลินทับทิม", position: "พนักงานบรรจุ", sheet: "P02" },
  { nameKey: "นาตยาณีอ่อนละออ", position: "พนักงานบรรจุ", sheet: "P02" },
  { nameKey: "อิศราสายรวมญาติ", position: "พนักงานบรรจุ", sheet: "P02" },
  { nameKey: "ตรีรัตน์ทะสูรย์", position: "พนักงานบรรจุ", sheet: "P02" },
  { nameKey: "ปิยะพลทำกินรวย", position: "พนักงานบรรจุ", sheet: "P02" },
  { nameKey: "วรรณฤดีนราแก้ว", position: "QC line", sheet: "P03" },
  { nameKey: "ณฐมนเงินใย", position: "หัวหน้าทีมบรรจุ", sheet: "P03" },
  { nameKey: "พรฑิราพรายโกยม", position: "หัวหน้าทีมบรรจุ", sheet: "P03" },
  { nameKey: "ชัยพัชร์บุญญาโชคพิพัฒน์", position: "หัวหน้าทีมผสม", sheet: "P03" },
  { nameKey: "ณรงค์ฤทธิ์ชูรอดวาด", position: "หัวหน้าทีมผสม", sheet: "P03" },
  { nameKey: "กฤตพลกำมา", position: "หัวหน้าทีมผสม", sheet: "P03" },
  { nameKey: "เกียรติศักดิ์นาคสมบูรณ์", position: "พนักงานผสม", sheet: "P03" },
  { nameKey: "ธนวัฒน์นาดี", position: "พนักงานผสม", sheet: "P03" },
  { nameKey: "สมบัติแสงอินทร์", position: "พนักงานผสม", sheet: "P03" },
  { nameKey: "ปรีชาวงษ์สีสา", position: "พนักงานผสม", sheet: "P03" },
  { nameKey: "สมิตาพัทร์ถะเถิงสุข", position: "พนักงานบรรจุ", sheet: "P03" },
  { nameKey: "กัญญาพัชร์ชิตบุตร", position: "หัวหน้าทีมบรรจุ", sheet: "P03" },
  { nameKey: "สุทัศชมเหิม", position: "พนักงานบรรจุ", sheet: "P03" },
  { nameKey: "กาญจนาโพธิ์สังข์", position: "พนักงานบรรจุ", sheet: "P03" },
  { nameKey: "กาญจนาจุลอุน", position: "พนักงานบรรจุ", sheet: "P03" },
  { nameKey: "จิตรอนงค์ศิริบุญรอด", position: "พนักงานบรรจุ", sheet: "P03" },
  { nameKey: "สุพรรณีวงษ์ดอกไม้", position: "พนักงานบรรจุ", sheet: "P03" },
  { nameKey: "มณีรัตน์มาลี", position: "พนักงานบรรจุ", sheet: "P03" },
  { nameKey: "เนยทวีชาติ", position: "พนักงานบรรจุ", sheet: "P03" },
  { nameKey: "ปรางทิพย์รุ่งเรืองจำเริญ", position: "พนักงานบรรจุ", sheet: "P03" },
  { nameKey: "วิศรุตเรืองเลิศ", position: "พนักงานบรรจุ", sheet: "P03" },
  { nameKey: "วาริชสูญสิ้นภัย", position: "พนักงานบรรจุ", sheet: "P03" },
  { nameKey: "ปรเมธสูญสิ้นภัย", position: "พนักงานบรรจุ", sheet: "P03" },
  { nameKey: "วิโรจน์แซ่อึ้ง", position: "พนักงานบรรจุ", sheet: "P03" },
  { nameKey: "ศิวัฒน์โหงวเกล็ด", position: "พนักงานบรรจุ", sheet: "P03" },
  { nameKey: "ไกรสรสีสุข", position: "พนักงานบรรจุ", sheet: "P03" },
  { nameKey: "อดิศรบ่อหน่าย", position: "พนักงานบรรจุ", sheet: "P03" },
  { nameKey: "ธนภัทรนายหน่อู", position: "พนักงานบรรจุ", sheet: "P03" },
  { nameKey: "วรายุวงษ์เหล็กอิ่ม", position: "พนักงานบรรจุ", sheet: "P03" },
  { nameKey: "เลี้ยงบุญเหลือ", position: "หัวหน้าทีมผสม", sheet: "P04" },
  { nameKey: "นิวัฒน์ชมเหิม", position: "พนักงานผสม", sheet: "P04" },
  { nameKey: "ปิยาภรณ์อ่อนสา", position: "QC line", sheet: "P04" },
  { nameKey: "เรณูย้วนประสิทธิ์", position: "หัวหน้าทีมบรรจุ", sheet: "P04" },
  { nameKey: "จำเนียรเจริญศิริ", position: "หัวหน้าทีมบรรจุ", sheet: "P04" },
  { nameKey: "เดือนฉายปิ่นประเสริฐ", position: "หัวหน้าทีมบรรจุ", sheet: "P04" },
  { nameKey: "สุวัฒน์มูลทรงเกียรติ", position: "พนักงานผสม", sheet: "P04" },
  { nameKey: "ธนิดาฤทธานันท์", position: "พนักงานบรรจุ", sheet: "P04" },
  { nameKey: "ธาริณีปราดเปรียว", position: "พนักงานบรรจุ", sheet: "P04" },
  { nameKey: "จิตติพรเปียแก้ว", position: "พนักงานบรรจุ", sheet: "P04" },
  { nameKey: "สิริลักษณ์สังภักดี", position: "พนักงานบรรจุ", sheet: "P04" },
  { nameKey: "จักรพันธ์นามแสง", position: "พนักงานบรรจุ", sheet: "P04" },
  { nameKey: "วาสนาเปลี่ยวกระโทก", position: "พนักงานบรรจุ", sheet: "P04" },
  { nameKey: "แจ่มจงใจงาม", position: "หัวหน้าทีมผสม", sheet: "P05" },
  { nameKey: "จักรกฤษณ์ผิวอ่อน", position: "หัวหน้าทีมผสม", sheet: "P05" },
  { nameKey: "ภูริตว่องไว", position: "พนักงานชั่งวัตถุดิบ", sheet: "P05" },
  { nameKey: "ฮวยม่วงดี", position: "หัวหน้าทีมบรรจุ", sheet: "P05" },
  { nameKey: "หนึ่งฤทัยพูลพิชัย", position: "QC line", sheet: "P05" },
  { nameKey: "ณัฐกานต์แก้วพลกรัง", position: "พนักงานยิงกระสอบ", sheet: "P05" },
  { nameKey: "วันวิสามาสุข", position: "พนักงานบรรจุ", sheet: "P05" },
  { nameKey: "วิลัยลักษณ์เทียมจิตร", position: "พนักงานบรรจุ", sheet: "P05" },
  { nameKey: "ณดาใหญ่ชุก", position: "พนักงานบรรจุ", sheet: "P05" },
  { nameKey: "ต่อชินทอง", position: "พนักงานชั่งวัตถุดิบ", sheet: "P05" },
  { nameKey: "วศินอ่อนสะอาด", position: "พนักงานขับรถโฟคลิฟท์", sheet: "P05" },
  { nameKey: "ชัยยันต์บุตรศรี", position: "พนักงานผสม", sheet: "P05" },
  { nameKey: "สมชายพิรานรัมย์", position: "พนักงานผสม", sheet: "P05" },
  { nameKey: "ปรัชญาสามเกษร", position: "พนักงานบรรจุ", sheet: "P05" },
  { nameKey: "ชัยวิวัฒน์เนียมศรีเพชร", position: "พนักงานบรรจุ", sheet: "P05" },
  { nameKey: "สถิตย์โสดา", position: "พนักงานบรรจุ", sheet: "P05" },
  { nameKey: "วราชัยอยู่ทอง", position: "พนักงานบรรจุ", sheet: "P05" },
  { nameKey: "เอกภพนาทรา", position: "พนักงานบรรจุ", sheet: "P05" },
  { nameKey: "พลธัชสะสมทรัพย์", position: "พนักงานบรรจุ", sheet: "P05" },
  { nameKey: "วันเพ็ญทานะมัย", position: "หัวหน้าทีมบรรจุ", sheet: "LDI" },
  { nameKey: "ศศิธรจงใจงาม", position: "หัวหน้าทีมบรรจุ", sheet: "LDI" },
  { nameKey: "ธัญชนกชื่นชม", position: "QC line", sheet: "LDI" },
  { nameKey: "มณฑิชาถะเกิงสุข", position: "พนักงานบรรจุ", sheet: "LDI" },
  { nameKey: "ศิริลักษณ์เจริญศิริ", position: "พนักงานบรรจุ", sheet: "LDI" },
  { nameKey: "รัชฏาภรณ์จันทร์ชุ่ม", position: "พนักงานบรรจุ", sheet: "LDI" },
  { nameKey: "สายบัวนราแก้ว", position: "พนักงานบรรจุ", sheet: "LDI" },
  { nameKey: "ปรารถนาทัพอาสา", position: "พนักงานบรรจุ", sheet: "LDI" },
  { nameKey: "ระพีพรเห็นสิน", position: "พนักงานบรรจุ", sheet: "LDI" },
  { nameKey: "ธเนศอินทรศร", position: "พนักงานบรรจุ", sheet: "LDI" },
  { nameKey: "สรชัชสิงห์กลั่น", position: "พนักงานบรรจุ", sheet: "LDI" },
  { nameKey: "วันชัยชวกิจศิริ", position: "พนักงานบรรจุ", sheet: "LDI" },
];
