import type { Employee } from "@/lib/skill-matrix";

export const IMPORTED_EMPLOYEES_2026: Employee[] = [
  {
    id: "employee-p01-001",
    employee_code: "P01-001",
    full_name: "นางมาลัย ปานทอง",
    position: "QC line",
    production_id: "production-p1",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 2 | Sheet: P01",
  },
  {
    id: "employee-p01-002",
    employee_code: "P01-002",
    full_name: "น.ส.มุณี สายกลิ่น",
    position: "หัวหน้าทีมบรรจุ",
    production_id: "production-p1",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 2 | Sheet: P01",
  },
  {
    id: "employee-p01-003",
    employee_code: "P01-003",
    full_name: "นางสำรวย เหล่าผา",
    position: "หัวหน้าทีมบรรจุ",
    production_id: "production-p1",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 2 | Sheet: P01",
  },
  {
    id: "employee-p01-004",
    employee_code: "P01-004",
    full_name: "น.ส.สงวนวงศ์ ยิ้มสะอาด",
    position: "หัวหน้าทีมบรรจุ",
    production_id: "production-p1",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 2 | Sheet: P01",
  },
  {
    id: "employee-p01-005",
    employee_code: "P01-005",
    full_name: "นายถิน ก้านทอง",
    position: "พนักงานผสม",
    production_id: "production-p1",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 2 | Sheet: P01",
  },
  {
    id: "employee-p01-006",
    employee_code: "P01-006",
    full_name: "นายสุทัศน์ แสงอินทร์",
    position: "หัวหน้าทีมผสม",
    production_id: "production-p1",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 2 | Sheet: P01",
  },
  {
    id: "employee-p01-007",
    employee_code: "P01-007",
    full_name: "นายดนตรี ก๋งแก้ว",
    position: "พนักงานผสม",
    production_id: "production-p1",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 2 | Sheet: P01",
  },
  {
    id: "employee-p01-008",
    employee_code: "P01-008",
    full_name: "นาย กิตติภณ แซ่ซุ้ง",
    position: "พนักงานผสม",
    production_id: "production-p1",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P01",
  },
  {
    id: "employee-p01-009",
    employee_code: "P01-009",
    full_name: "น.ส.อุไรวรรณ จันทร์ลอย",
    position: "พนักงานบรรจุ",
    production_id: "production-p1",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: P01",
  },
  {
    id: "employee-p01-010",
    employee_code: "P01-010",
    full_name: "น.ส.ปณัชช์ เอี่ยมเอม",
    position: "พนักงานบรรจุ",
    production_id: "production-p1",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: P01",
  },
  {
    id: "employee-p01-011",
    employee_code: "P01-011",
    full_name: "นางสาวอัญชเกด อุปสิทธิ์",
    position: "พนักงานบรรจุ",
    production_id: "production-p1",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: P01",
  },
  {
    id: "employee-p01-012",
    employee_code: "P01-012",
    full_name: "น.ส.กาญจนา ล้อมสินทรัพย์",
    position: "พนักงานบรรจุ",
    production_id: "production-p1",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: P01",
  },
  {
    id: "employee-p01-013",
    employee_code: "P01-013",
    full_name: "น.ส.ศราวณี สุกสี",
    position: "พนักงานบรรจุ",
    production_id: "production-p1",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: P01",
  },
  {
    id: "employee-p01-014",
    employee_code: "P01-014",
    full_name: "นายวรา ใจเยือกเย็น",
    position: "พนักงานบรรจุ",
    production_id: "production-p1",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P01",
  },
  {
    id: "employee-p01-015",
    employee_code: "P01-015",
    full_name: "นายทัศพร มณีพันธ์",
    position: "พนักงานบรรจุ",
    production_id: "production-p1",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P01",
  },
  {
    id: "employee-p01-016",
    employee_code: "P01-016",
    full_name: "นายสันติ แก้วบุญเพิ่ม",
    position: "พนักงานบรรจุ",
    production_id: "production-p1",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P01",
  },
  {
    id: "employee-p01-017",
    employee_code: "P01-017",
    full_name: "นายธนวัฒน์ กลิ่นขจร",
    position: "พนักงานบรรจุ",
    production_id: "production-p1",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P01",
  },
  {
    id: "employee-p02-001",
    employee_code: "P02-001",
    full_name: "น.ส.วาสนา ชั้นสกุณี",
    position: "พนักงานเอกสาร",
    production_id: "production-p2",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 2 | Sheet: P02",
  },
  {
    id: "employee-p02-002",
    employee_code: "P02-002",
    full_name: "น.ส.แสงทอง กองสี",
    position: "QC line",
    production_id: "production-p2",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 2 | Sheet: P02",
  },
  {
    id: "employee-p02-003",
    employee_code: "P02-003",
    full_name: "นายพิชิต พัดเย็น",
    position: "พนักงานผสม",
    production_id: "production-p2",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 2 | Sheet: P02",
  },
  {
    id: "employee-p02-004",
    employee_code: "P02-004",
    full_name: "นายนุชานนท์ ใจบุญ",
    position: "พนักงานชั่งวัตถุดิบ",
    production_id: "production-p2",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 2 | Sheet: P02",
  },
  {
    id: "employee-p02-005",
    employee_code: "P02-005",
    full_name: "น.ส.พรรณี ออมใช้",
    position: "หัวหน้าทีมบรรจุ",
    production_id: "production-p2",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 2 | Sheet: P02",
  },
  {
    id: "employee-p02-006",
    employee_code: "P02-006",
    full_name: "นายไพรัช อยู่มากญาติ",
    position: "พนักงานขับรถโฟคลิฟท์",
    production_id: "production-p2",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P02",
  },
  {
    id: "employee-p02-007",
    employee_code: "P02-007",
    full_name: "นายพรพิทักษ์ จันทร์ตราชู",
    position: "พนักงานขับรถโฟคลิฟท์",
    production_id: "production-p2",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P02",
  },
  {
    id: "employee-p02-008",
    employee_code: "P02-008",
    full_name: "นางสาวปาลิตา อุไรงาม",
    position: "พนักงานยิงกระสอบ",
    production_id: "production-p2",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: P02",
  },
  {
    id: "employee-p02-009",
    employee_code: "P02-009",
    full_name: "นายชิดดนัย ใจหลัก",
    position: "พนักงานผสม",
    production_id: "production-p2",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P02",
  },
  {
    id: "employee-p02-010",
    employee_code: "P02-010",
    full_name: "นายนิธิธีร์ ไพโรจน์",
    position: "พนักงานผสม",
    production_id: "production-p2",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P02",
  },
  {
    id: "employee-p02-011",
    employee_code: "P02-011",
    full_name: "นายสถาพร เกียงยง",
    position: "พนักงานผสม",
    production_id: "production-p2",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P02",
  },
  {
    id: "employee-p02-012",
    employee_code: "P02-012",
    full_name: "นายธีระศักดิ์ ดวงรัตน์",
    position: "พนักงานผสม",
    production_id: "production-p2",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P02",
  },
  {
    id: "employee-p02-013",
    employee_code: "P02-013",
    full_name: "นายกฤษฎาพัฒน์ เจริญรอย",
    position: "พนักงานผสม",
    production_id: "production-p2",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P02",
  },
  {
    id: "employee-p02-014",
    employee_code: "P02-014",
    full_name: "นายวุฒิวสุ คำสุข",
    position: "พนักงานผสม",
    production_id: "production-p2",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P02",
  },
  {
    id: "employee-p02-015",
    employee_code: "P02-015",
    full_name: "น.ส.ฉัตรศิริ พันที",
    position: "พนักงานบรรจุ",
    production_id: "production-p2",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: P02",
  },
  {
    id: "employee-p02-016",
    employee_code: "P02-016",
    full_name: "น.ส.การเกด พริ้งเพชร",
    position: "พนักงานบรรจุ",
    production_id: "production-p2",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: P02",
  },
  {
    id: "employee-p02-017",
    employee_code: "P02-017",
    full_name: "น.ส.เกวลิน ทับทิม",
    position: "พนักงานบรรจุ",
    production_id: "production-p2",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: P02",
  },
  {
    id: "employee-p02-018",
    employee_code: "P02-018",
    full_name: "น.ส.นาตยาณี อ่อนละออ",
    position: "พนักงานบรรจุ",
    production_id: "production-p2",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: P02",
  },
  {
    id: "employee-p02-019",
    employee_code: "P02-019",
    full_name: "นายอิศรา สายรวมญาติ",
    position: "พนักงานบรรจุ",
    production_id: "production-p2",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P02",
  },
  {
    id: "employee-p02-020",
    employee_code: "P02-020",
    full_name: "นายตรีรัตน์ ทะสูรย์",
    position: "พนักงานบรรจุ",
    production_id: "production-p2",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P02",
  },
  {
    id: "employee-p02-021",
    employee_code: "P02-021",
    full_name: "นาย ปิยะพล ทำกินรวย",
    position: "พนักงานบรรจุ",
    production_id: "production-p2",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P02",
  },
  {
    id: "employee-p03-001",
    employee_code: "P03-001",
    full_name: "น.ส.วรรณฤดี นราแก้ว",
    position: "QC line",
    production_id: "production-p3",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 2 | Sheet: P03",
  },
  {
    id: "employee-p03-002",
    employee_code: "P03-002",
    full_name: "น.ส.ณฐมน เงินใย",
    position: "หัวหน้าทีมบรรจุ",
    production_id: "production-p3",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 2 | Sheet: P03",
  },
  {
    id: "employee-p03-003",
    employee_code: "P03-003",
    full_name: "น.ส.พรฑิรา พรายโกยม",
    position: "หัวหน้าทีมบรรจุ",
    production_id: "production-p3",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 2 | Sheet: P03",
  },
  {
    id: "employee-p03-004",
    employee_code: "P03-004",
    full_name: "นาย ชัยพัชร์ บุญญาโชคพิพัฒน์",
    position: "หัวหน้าทีมผสม",
    production_id: "production-p3",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 2 | Sheet: P03",
  },
  {
    id: "employee-p03-005",
    employee_code: "P03-005",
    full_name: "นายณรงค์ฤทธิ์ ชูรอดวาด",
    position: "หัวหน้าทีมผสม",
    production_id: "production-p3",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 2 | Sheet: P03",
  },
  {
    id: "employee-p03-006",
    employee_code: "P03-006",
    full_name: "นายกฤตพล กำมา",
    position: "หัวหน้าทีมผสม",
    production_id: "production-p3",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 2 | Sheet: P03",
  },
  {
    id: "employee-p03-007",
    employee_code: "P03-007",
    full_name: "นายเกียรติศักดิ์ นาคสมบูรณ์",
    position: "พนักงานผสม",
    production_id: "production-p3",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P03",
  },
  {
    id: "employee-p03-008",
    employee_code: "P03-008",
    full_name: "นายธนวัฒน์ นาดี",
    position: "พนักงานผสม",
    production_id: "production-p3",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P03",
  },
  {
    id: "employee-p03-009",
    employee_code: "P03-009",
    full_name: "นาย สมบัติ แสงอินทร์",
    position: "พนักงานผสม",
    production_id: "production-p3",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P03",
  },
  {
    id: "employee-p03-010",
    employee_code: "P03-010",
    full_name: "นายปรีชา วงษ์สีสา",
    position: "พนักงานผสม",
    production_id: "production-p3",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P03",
  },
  {
    id: "employee-p03-011",
    employee_code: "P03-011",
    full_name: "นางสมิตาพัทร์ ถะเถิงสุข",
    position: "พนักงานบรรจุ",
    production_id: "production-p3",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: P03",
  },
  {
    id: "employee-p03-012",
    employee_code: "P03-012",
    full_name: "น.ส.กัญญาพัชร์ ชิตบุตร",
    position: "หัวหน้าทีมบรรจุ",
    production_id: "production-p3",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 2 | Sheet: P03",
  },
  {
    id: "employee-p03-013",
    employee_code: "P03-013",
    full_name: "นางสุทัศ ชมเหิม",
    position: "พนักงานบรรจุ",
    production_id: "production-p3",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: P03",
  },
  {
    id: "employee-p03-014",
    employee_code: "P03-014",
    full_name: "น.ส.กาญจนา โพธิ์สังข์",
    position: "พนักงานบรรจุ",
    production_id: "production-p3",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: P03",
  },
  {
    id: "employee-p03-015",
    employee_code: "P03-015",
    full_name: "น.ส.กาญจนา จุลอุน",
    position: "พนักงานบรรจุ",
    production_id: "production-p3",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: P03",
  },
  {
    id: "employee-p03-016",
    employee_code: "P03-016",
    full_name: "น.ส.จิตรอนงค์ ศิริบุญรอด",
    position: "พนักงานบรรจุ",
    production_id: "production-p3",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: P03",
  },
  {
    id: "employee-p03-017",
    employee_code: "P03-017",
    full_name: "น.ส.สุพรรณี วงษ์ดอกไม้",
    position: "พนักงานบรรจุ",
    production_id: "production-p3",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: P03",
  },
  {
    id: "employee-p03-018",
    employee_code: "P03-018",
    full_name: "น.ส.มณีรัตน์ มาลี",
    position: "พนักงานบรรจุ",
    production_id: "production-p3",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: P03",
  },
  {
    id: "employee-p03-019",
    employee_code: "P03-019",
    full_name: "น.ส.เนย ทวีชาติ",
    position: "พนักงานบรรจุ",
    production_id: "production-p3",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: P03",
  },
  {
    id: "employee-p03-020",
    employee_code: "P03-020",
    full_name: "น.ส.ปรางทิพย์ รุ่งเรืองจำเริญ",
    position: "พนักงานบรรจุ",
    production_id: "production-p3",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: P03",
  },
  {
    id: "employee-p03-021",
    employee_code: "P03-021",
    full_name: "นายวิศรุต เรืองเลิศ",
    position: "พนักงานบรรจุ",
    production_id: "production-p3",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P03",
  },
  {
    id: "employee-p03-022",
    employee_code: "P03-022",
    full_name: "นายวาริช สูญสิ้นภัย",
    position: "พนักงานบรรจุ",
    production_id: "production-p3",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P03",
  },
  {
    id: "employee-p03-023",
    employee_code: "P03-023",
    full_name: "นายปรเมธ สูญสิ้นภัย",
    position: "พนักงานบรรจุ",
    production_id: "production-p3",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P03",
  },
  {
    id: "employee-p03-024",
    employee_code: "P03-024",
    full_name: "นายวิโรจน์ แซ่อึ้ง",
    position: "พนักงานบรรจุ",
    production_id: "production-p3",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P03",
  },
  {
    id: "employee-p03-025",
    employee_code: "P03-025",
    full_name: "นายศิวัฒน์ โหงวเกล็ด",
    position: "พนักงานบรรจุ",
    production_id: "production-p3",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P03",
  },
  {
    id: "employee-p03-026",
    employee_code: "P03-026",
    full_name: "นายไกรสร สีสุข",
    position: "พนักงานบรรจุ",
    production_id: "production-p3",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P03",
  },
  {
    id: "employee-p03-027",
    employee_code: "P03-027",
    full_name: "นายอดิศร บ่อหน่าย",
    position: "พนักงานบรรจุ",
    production_id: "production-p3",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P03",
  },
  {
    id: "employee-p03-028",
    employee_code: "P03-028",
    full_name: "นายธนภัทร นายหน่อู",
    position: "พนักงานบรรจุ",
    production_id: "production-p3",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P03",
  },
  {
    id: "employee-p03-029",
    employee_code: "P03-029",
    full_name: "นายวรายุวงษ์ เหล็กอิ่ม",
    position: "พนักงานบรรจุ",
    production_id: "production-p3",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P03",
  },
  {
    id: "employee-p04-001",
    employee_code: "P04-001",
    full_name: "นายเลี้ยง บุญเหลือ",
    position: "หัวหน้าทีมผสม",
    production_id: "production-p4",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 2 | Sheet: P04",
  },
  {
    id: "employee-p04-002",
    employee_code: "P04-002",
    full_name: "นายนิวัฒน์ ชมเหิม",
    position: "พนักงานผสม",
    production_id: "production-p4",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 2 | Sheet: P04",
  },
  {
    id: "employee-p04-003",
    employee_code: "P04-003",
    full_name: "น.ส.ปิยาภรณ์ อ่อนสา",
    position: "QC line",
    production_id: "production-p4",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 2 | Sheet: P04",
  },
  {
    id: "employee-p04-004",
    employee_code: "P04-004",
    full_name: "น.ส.เรณู ย้วนประสิทธิ์",
    position: "หัวหน้าทีมบรรจุ",
    production_id: "production-p4",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 2 | Sheet: P04",
  },
  {
    id: "employee-p04-005",
    employee_code: "P04-005",
    full_name: "น.ส.จำเนียร เจริญศิริ",
    position: "หัวหน้าทีมบรรจุ",
    production_id: "production-p4",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 2 | Sheet: P04",
  },
  {
    id: "employee-p04-006",
    employee_code: "P04-006",
    full_name: "น.ส.เดือนฉาย ปิ่นประเสริฐ",
    position: "หัวหน้าทีมบรรจุ",
    production_id: "production-p4",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 2 | Sheet: P04",
  },
  {
    id: "employee-p04-007",
    employee_code: "P04-007",
    full_name: "นายสุวัฒน์ มูลทรงเกียรติ",
    position: "พนักงานผสม",
    production_id: "production-p4",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P04",
  },
  {
    id: "employee-p04-008",
    employee_code: "P04-008",
    full_name: "น.ส.ธนิดา ฤทธานันท์",
    position: "พนักงานบรรจุ",
    production_id: "production-p4",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: P04",
  },
  {
    id: "employee-p04-009",
    employee_code: "P04-009",
    full_name: "น.ส.ธาริณี ปราดเปรียว",
    position: "พนักงานบรรจุ",
    production_id: "production-p4",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: P04",
  },
  {
    id: "employee-p04-010",
    employee_code: "P04-010",
    full_name: "น.ส.จิตติพร เปียแก้ว",
    position: "พนักงานบรรจุ",
    production_id: "production-p4",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: P04",
  },
  {
    id: "employee-p04-011",
    employee_code: "P04-011",
    full_name: "น.ส.สิริลักษณ์ สังภักดี",
    position: "พนักงานบรรจุ",
    production_id: "production-p4",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: P04",
  },
  {
    id: "employee-p04-012",
    employee_code: "P04-012",
    full_name: "นายจักรพันธ์ นามแสง",
    position: "พนักงานบรรจุ",
    production_id: "production-p4",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P04",
  },
  {
    id: "employee-p04-013",
    employee_code: "P04-013",
    full_name: "นายวาสนา เปลี่ยวกระโทก",
    position: "พนักงานบรรจุ",
    production_id: "production-p4",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P04",
  },
  {
    id: "employee-p05-001",
    employee_code: "P05-001",
    full_name: "นายแจ่ม จงใจงาม",
    position: "หัวหน้าทีมผสม",
    production_id: "production-p5",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 2 | Sheet: P05",
  },
  {
    id: "employee-p05-002",
    employee_code: "P05-002",
    full_name: "นายจักรกฤษณ์ ผิวอ่อน",
    position: "หัวหน้าทีมผสม",
    production_id: "production-p5",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 2 | Sheet: P05",
  },
  {
    id: "employee-p05-003",
    employee_code: "P05-003",
    full_name: "นายภูริต ว่องไว",
    position: "พนักงานชั่งวัตถุดิบ",
    production_id: "production-p5",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 2 | Sheet: P05",
  },
  {
    id: "employee-p05-004",
    employee_code: "P05-004",
    full_name: "น.ส.ฮวย ม่วงดี",
    position: "หัวหน้าทีมบรรจุ",
    production_id: "production-p5",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 2 | Sheet: P05",
  },
  {
    id: "employee-p05-005",
    employee_code: "P05-005",
    full_name: "น.ส.หนึ่งฤทัย พูลพิชัย",
    position: "QC line",
    production_id: "production-p5",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 2 | Sheet: P05",
  },
  {
    id: "employee-p05-006",
    employee_code: "P05-006",
    full_name: "น.ส.ณัฐกานต์ แก้วพลกรัง",
    position: "พนักงานยิงกระสอบ",
    production_id: "production-p5",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: P05",
  },
  {
    id: "employee-p05-007",
    employee_code: "P05-007",
    full_name: "น.ส.วันวิสา มาสุข",
    position: "พนักงานบรรจุ",
    production_id: "production-p5",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: P05",
  },
  {
    id: "employee-p05-008",
    employee_code: "P05-008",
    full_name: "น.ส.วิลัยลักษณ์ เทียมจิตร",
    position: "พนักงานบรรจุ",
    production_id: "production-p5",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: P05",
  },
  {
    id: "employee-p05-009",
    employee_code: "P05-009",
    full_name: "นส.ณดา ใหญ่ชุก",
    position: "พนักงานบรรจุ",
    production_id: "production-p5",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: P05",
  },
  {
    id: "employee-p05-010",
    employee_code: "P05-010",
    full_name: "นายต่อ ชินทอง",
    position: "พนักงานชั่งวัตถุดิบ",
    production_id: "production-p5",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P05",
  },
  {
    id: "employee-p05-011",
    employee_code: "P05-011",
    full_name: "นายวศิน อ่อนสะอาด",
    position: "พนักงานขับรถโฟคลิฟท์",
    production_id: "production-p5",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P05",
  },
  {
    id: "employee-p05-012",
    employee_code: "P05-012",
    full_name: "นายชัยยันต์ บุตรศรี",
    position: "พนักงานผสม",
    production_id: "production-p5",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P05",
  },
  {
    id: "employee-p05-013",
    employee_code: "P05-013",
    full_name: "นายสมชาย พิรานรัมย์",
    position: "พนักงานผสม",
    production_id: "production-p5",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P05",
  },
  {
    id: "employee-p05-014",
    employee_code: "P05-014",
    full_name: "นายปรัชญา สามเกษร",
    position: "พนักงานบรรจุ",
    production_id: "production-p5",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P05",
  },
  {
    id: "employee-p05-015",
    employee_code: "P05-015",
    full_name: "นายชัยวิวัฒน์ เนียมศรีเพชร",
    position: "พนักงานบรรจุ",
    production_id: "production-p5",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P05",
  },
  {
    id: "employee-p05-016",
    employee_code: "P05-016",
    full_name: "นายสถิตย์ โสดา",
    position: "พนักงานบรรจุ",
    production_id: "production-p5",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P05",
  },
  {
    id: "employee-p05-017",
    employee_code: "P05-017",
    full_name: "นายวราชัย อยู่ทอง",
    position: "พนักงานบรรจุ",
    production_id: "production-p5",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P05",
  },
  {
    id: "employee-p05-018",
    employee_code: "P05-018",
    full_name: "นายเอกภพ นาทรา",
    position: "พนักงานบรรจุ",
    production_id: "production-p5",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P05",
  },
  {
    id: "employee-p05-019",
    employee_code: "P05-019",
    full_name: "นายพลธัช สะสมทรัพย์",
    position: "พนักงานบรรจุ",
    production_id: "production-p5",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: P05",
  },
  {
    id: "employee-ldi-001",
    employee_code: "LDI-001",
    full_name: "น.ส.วันเพ็ญ ทานะมัย",
    position: "หัวหน้าทีมบรรจุ",
    production_id: "production-ldi",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 2 | Sheet: LDI",
  },
  {
    id: "employee-ldi-002",
    employee_code: "LDI-002",
    full_name: "น.ส.ศศิธร จงใจงาม",
    position: "หัวหน้าทีมบรรจุ",
    production_id: "production-ldi",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 2,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 2 | Sheet: LDI",
  },
  {
    id: "employee-ldi-003",
    employee_code: "LDI-003",
    full_name: "น.ส. ธัญชนก ชื่นชม",
    position: "QC line",
    production_id: "production-ldi",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: LDI",
  },
  {
    id: "employee-ldi-004",
    employee_code: "LDI-004",
    full_name: "น.ส.มณฑิชา ถะเกิงสุข",
    position: "พนักงานบรรจุ",
    production_id: "production-ldi",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: LDI",
  },
  {
    id: "employee-ldi-005",
    employee_code: "LDI-005",
    full_name: "น.ส.ศิริลักษณ์ เจริญศิริ",
    position: "พนักงานบรรจุ",
    production_id: "production-ldi",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: LDI",
  },
  {
    id: "employee-ldi-006",
    employee_code: "LDI-006",
    full_name: "น.ส.รัชฏาภรณ์ จันทร์ชุ่ม",
    position: "พนักงานบรรจุ",
    production_id: "production-ldi",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: LDI",
  },
  {
    id: "employee-ldi-007",
    employee_code: "LDI-007",
    full_name: "น.ส.สายบัว นราแก้ว",
    position: "พนักงานบรรจุ",
    production_id: "production-ldi",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: LDI",
  },
  {
    id: "employee-ldi-008",
    employee_code: "LDI-008",
    full_name: "น.ส.ปรารถนา ทัพอาสา",
    position: "พนักงานบรรจุ",
    production_id: "production-ldi",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: LDI",
  },
  {
    id: "employee-ldi-009",
    employee_code: "LDI-009",
    full_name: "น.ส.ระพีพร เห็นสิน",
    position: "พนักงานบรรจุ",
    production_id: "production-ldi",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: หญิง | ระดับจากไฟล์: JB 1 | Sheet: LDI",
  },
  {
    id: "employee-ldi-010",
    employee_code: "LDI-010",
    full_name: "นายธเนศ อินทรศร",
    position: "พนักงานบรรจุ",
    production_id: "production-ldi",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: LDI",
  },
  {
    id: "employee-ldi-011",
    employee_code: "LDI-011",
    full_name: "นายสรชัช สิงห์กลั่น",
    position: "พนักงานบรรจุ",
    production_id: "production-ldi",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: LDI",
  },
  {
    id: "employee-ldi-012",
    employee_code: "LDI-012",
    full_name: "นายวันชัย ชวกิจศิริ",
    position: "พนักงานบรรจุ",
    production_id: "production-ldi",
    start_work_date: null,
    jd_training_passed: false,
    wi_training_passed: false,
    competency_level: 1,
    status: "ปฏิบัติงาน",
    remark: "เพศ: ชาย | ระดับจากไฟล์: JB 1 | Sheet: LDI",
  },
];
